[validator]
exclude_patterns = [".git", "node_modules", "*.tmp", "templates"]
log_level = "warning"
report_format = "markdown"
is_validate = true
is_fail_on_error = true
external_timeout_sec = 5
max_threads_number = 1
hosts_to_ignore = ["localhost", "127.0.0.1"]
is_skip_external = true
report_include_files = true
validate_external_anchors = false
external_parsing_timeout_sec = 10
external_parsing_user_agent = "'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'"