[validator]
exclude_patterns = [".git", "node_modules", "*.tmp"]
log_level = "warning"
report_format = "markdown"
is_validate = true
is_fail_on_error = true
external_timeout_sec = 5
max_threads_number = 1
hosts_to_ignore = ["localhost", "127.0.0.1"]
is_skip_external = true